# This will pack UI and Backend to one single package and will release it to GitHub and Docker
name: Generate Combined Release

on:
  push:
    branches:
      - main
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Frontend
        run: |
            cd consumption_tracker_ui
            npm install
            npm run build

      - name: Copy ui to package
        run: |
            cp -r consumption_tracker_ui/dist/ src/main/resources/public
            cd src/main/resources/public
            ls -l

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build Backend
        run: mvn -B package --file pom.xml -DskipTests

      - name: prepare Docker Build
        run: |
            cd target
            JAR_FILE=`ls consumptionTracker-*.jar`
            mv ${JAR_FILE} consumptionTracker_dockerBuild.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        run: |
            docker build . --file Dockerfile --tag hohin/consumtion_tracker:latest --tag hohin/consumtion_tracker:0.1.0
            docker push hohin/consumtion_tracker --all-tags



