# This will pack UI and Backend to one single package and will release it to GitHub and Docker
name: Generate Combined Release

on:
  push:
    branches:
      - main
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Frontend
        run: |
            cd consumption_tracker_ui
            npm install
            npm run build

      - name: Copy ui to package
        run: |
            cp -r consumption_tracker_ui/dist/ src/main/resources/public
            cd target/classes/public
            ls -l

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
